version: '3.7'
services: 
  water_usage_import:
    image: 'thermostat_mqtt:latest'
    container_name: 'thermostat_mqtt'
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    network_mode: host
    environment:
      - TZ=America/New_York
    volumes:
      - /data/thermostat_mqtt/config.yaml:/data/config.yaml:ro
    restart: unless-stopped
    user: root